name: hand_gesture_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Core Libraries
  - numpy=1.24.3
  - pandas=2.0.3
  - pillow=10.0.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.65.0
  
  # Computer Vision
  - opencv=4.8.0
  - mediapipe=0.10.7
  
  # Deep Learning
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchmetrics=1.2.0
  
  # Development
  - jupyter=1.0.0
  - ipykernel=6.25.0
  
  # Pip packages
  - pip:
    - torchsummary==1.5.1
    - torchviz==0.0.2
    - thop==0.1.1.post2209072238